quarkus.http.port=8080

quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=postgresql://postgres:5432/creditdb
quarkus.datasource.username=credituser
quarkus.datasource.password=creditpass
quarkus.hibernate-orm.database.generation=none

quarkus.grpc.clients.risk-service.host=risk-service
quarkus.grpc.clients.risk-service.port=9000

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5173
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization
quarkus.http.cors.access-control-max-age=24H

quarkus.http.access-log.enabled=true
quarkus.http.access-log.pattern=%h %r %s %b %D

quarkus.log.level=INFO
quarkus.log.category."com.credit.orchestrator".level=DEBUG

%prod.quarkus.datasource.reactive.url=postgresql://postgres:5432/creditdb
%prod.quarkus.grpc.clients.risk-service.host=risk-service
%prod.quarkus.grpc.clients.risk-service.port=9000

%dev.quarkus.datasource.reactive.url=postgresql://localhost:5432/creditdb
%dev.quarkus.grpc.clients.risk-service.host=localhost
%dev.quarkus.grpc.clients.risk-service.port=9000
